name: Try log secrets

on:
    pull_request:
      branches: ["main"]

  jobs:
    log:
      runs-on: ubuntu-latest

      steps:
       - name: log secret
       run: echo ${{ secrets.TEST_SECRET }}